export type PermissionTemplateScope = 'platform' | 'tenant';

export type PermissionTemplate = {
  code: string;
  name: string;
  description: string;
  scope: PermissionTemplateScope;
  riskLevel: 'low' | 'medium' | 'high';
  recommendedFor: string[];
  permissionCodes: string[];
};

export const permissionTemplates: PermissionTemplate[] = [
  {
    code: 'PLATFORM_OPERATOR',
    name: 'Platform Operator',
    description: 'Full platform administration across tenants, features, settings, audit, and operational oversight.',
    scope: 'platform',
    riskLevel: 'high',
    recommendedFor: ['Super administrators', 'Platform owners'],
    permissionCodes: [
      'platform.tenants.manage',
      'platform.features.manage',
      'platform.settings.manage',
      'platform.audit.read',
      'dashboard.read',
      'analytics.read',
      'outbox.read',
      'outbox.process',
    ],
  },
  {
    code: 'PLATFORM_SUPPORT_READONLY',
    name: 'Platform Support Readonly',
    description: 'Readonly platform support posture for tenant triage without write access.',
    scope: 'platform',
    riskLevel: 'medium',
    recommendedFor: ['Support analysts', 'Implementation support'],
    permissionCodes: [
      'platform.audit.read',
      'dashboard.read',
      'analytics.read',
      'outbox.read',
    ],
  },
  {
    code: 'TENANT_ADMIN_FULL',
    name: 'Tenant Admin Full',
    description: 'Complete tenant administration for IAM, workforce, documents, workflows, dashboards, and tenant settings.',
    scope: 'tenant',
    riskLevel: 'high',
    recommendedFor: ['Tenant administrators', 'Implementation leads'],
    permissionCodes: [
      'tenants.settings.read',
      'tenants.settings.write',
      'tenants.branding.read',
      'tenants.branding.write',
      'tenants.features.read',
      'tenants.features.write',
      'tenants.subscription.read',
      'tenants.subscription.write',
      'iam.users.read',
      'iam.users.write',
      'iam.roles.read',
      'iam.roles.write',
      'iam.permissions.read',
      'organization.read',
      'organization.write',
      'cost-centers.read',
      'cost-centers.write',
      'persons.read',
      'persons.write',
      'persons.sensitive.read',
      'employees.read',
      'employees.write',
      'employees.invite',
      'employees.transfer',
      'employees.suspend',
      'employees.separate',
      'assignments.read',
      'assignments.write',
      'positions.read',
      'positions.write',
      'workforce-actions.read',
      'workforce-actions.write',
      'workflows.read',
      'workflows.write',
      'approvals.read',
      'approvals.process',
      'documents.read',
      'documents.write',
      'documents.verify',
      'notifications.read',
      'notifications.write',
      'forms.read',
      'forms.write',
      'scheduling.read',
      'scheduling.write',
      'scheduling.team.write',
      'scheduling.self',
      'scheduling.overtime.approve',
      'attendance.read',
      'attendance.write',
      'attendance.team.write',
      'attendance.self',
      'attendance.controls.write',
      'attendance.reports.read',
      'attendance.exceptions.approve',
      'attendance.timesheets.approve',
      'leave.self',
      'leave.team.read',
      'leave.team.write',
      'leave.approve',
      'leave.policy.write',
      'leave.reports.read',
      'audit.read',
      'activity.read',
      'timeline.read',
      'outbox.read',
      'outbox.process',
      'content.read',
      'content.write',
      'content.publish',
      'dashboard.read',
      'dashboard.write',
      'analytics.read',
      'analytics.write',
    ],
  },
  {
    code: 'HR_OPERATIONS',
    name: 'HR Operations',
    description: 'Day-to-day workforce administration across people data, employees, assignments, documents, and approvals.',
    scope: 'tenant',
    riskLevel: 'high',
    recommendedFor: ['HR administrators', 'People operations'],
    permissionCodes: [
      'tenants.settings.read',
      'tenants.branding.read',
      'tenants.features.read',
      'iam.users.read',
      'iam.roles.read',
      'iam.permissions.read',
      'organization.read',
      'organization.write',
      'cost-centers.read',
      'cost-centers.write',
      'persons.read',
      'persons.write',
      'persons.sensitive.read',
      'employees.read',
      'employees.write',
      'employees.invite',
      'employees.transfer',
      'employees.suspend',
      'employees.separate',
      'assignments.read',
      'assignments.write',
      'positions.read',
      'positions.write',
      'workforce-actions.read',
      'workforce-actions.write',
      'workflows.read',
      'approvals.read',
      'approvals.process',
      'documents.read',
      'documents.write',
      'documents.verify',
      'notifications.read',
      'notifications.write',
      'forms.read',
      'forms.write',
      'scheduling.read',
      'scheduling.write',
      'scheduling.team.write',
      'scheduling.self',
      'scheduling.overtime.approve',
      'attendance.read',
      'attendance.write',
      'attendance.team.write',
      'attendance.self',
      'attendance.controls.write',
      'attendance.reports.read',
      'attendance.exceptions.approve',
      'attendance.timesheets.approve',
      'leave.self',
      'leave.team.read',
      'leave.team.write',
      'leave.approve',
      'leave.policy.write',
      'leave.reports.read',
      'audit.read',
      'activity.read',
      'timeline.read',
      'content.read',
      'content.write',
      'dashboard.read',
      'dashboard.write',
      'analytics.read',
      'analytics.write',
    ],
  },
  {
    code: 'MANAGER_SELF_SERVICE',
    name: 'Manager Self Service',
    description: 'Manager workspace for team visibility, approval tasks, timeline, documents, and dashboard access.',
    scope: 'tenant',
    riskLevel: 'medium',
    recommendedFor: ['Managers', 'Team leads'],
    permissionCodes: [
      'organization.read',
      'cost-centers.read',
      'persons.read',
      'employees.read',
      'assignments.read',
      'positions.read',
      'workforce-actions.read',
      'approvals.read',
      'approvals.process',
      'documents.read',
      'notifications.read',
      'forms.read',
      'scheduling.team.write',
      'scheduling.self',
      'scheduling.overtime.approve',
      'attendance.team.write',
      'attendance.self',
      'attendance.reports.read',
      'attendance.exceptions.approve',
      'attendance.timesheets.approve',
      'leave.self',
      'leave.team.read',
      'leave.team.write',
      'leave.approve',
      'leave.reports.read',
      'timeline.read',
      'content.read',
      'dashboard.read',
    ],
  },
  {
    code: 'DOCUMENT_COMPLIANCE',
    name: 'Document Compliance',
    description: 'Document verification, expiration review, and compliance queue management.',
    scope: 'tenant',
    riskLevel: 'medium',
    recommendedFor: ['Compliance teams', 'HR document reviewers'],
    permissionCodes: [
      'employees.read',
      'persons.read',
      'documents.read',
      'documents.write',
      'documents.verify',
      'notifications.read',
      'audit.read',
      'timeline.read',
      'dashboard.read',
    ],
  },
  {
    code: 'WORKFLOW_STEWARD',
    name: 'Workflow Steward',
    description: 'Workflow building and approval operations for tenant process owners.',
    scope: 'tenant',
    riskLevel: 'high',
    recommendedFor: ['Workflow administrators', 'Process owners'],
    permissionCodes: [
      'workflows.read',
      'workflows.write',
      'approvals.read',
      'approvals.process',
      'workforce-actions.read',
      'notifications.read',
      'audit.read',
      'timeline.read',
      'dashboard.read',
    ],
  },
  {
    code: 'EMPLOYEE_SELF_SERVICE',
    name: 'Employee Self Service',
    description: 'Basic employee self-service access to personal notices, dashboard entry, and published HR guides.',
    scope: 'tenant',
    riskLevel: 'low',
    recommendedFor: ['Employees', 'Contractors'],
    permissionCodes: [
      'notifications.read',
      'content.read',
      'dashboard.read',
      'scheduling.self',
      'attendance.self',
      'leave.self',
    ],
  },
  {
    code: 'AUDITOR_READONLY',
    name: 'Auditor Readonly',
    description: 'Readonly audit, activity, timeline, dashboard, and analytics access for compliance review.',
    scope: 'tenant',
    riskLevel: 'medium',
    recommendedFor: ['Auditors', 'Compliance reviewers'],
    permissionCodes: [
      'audit.read',
      'activity.read',
      'timeline.read',
      'dashboard.read',
      'analytics.read',
      'outbox.read',
    ],
  },
];
